### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by andreshg112** [gorums/generator-angular-2-crud#21]
[at-loader] Checking finished with 75 errors
[at-loader] node_modules/@angular/core/src/facade/lang.d.ts:12:17
    'Map' only refers to a type, but is being used as a value here.

[at-loader] node_modules/@angular/core/src/facade/lang.d.ts:13:17
    'Set' only refers to a type, but is being used as a value here.

[at-loader] node_modules/@types/core-js/index.d.ts:47:36
    Cannot find name 'Iterable'.

[at-loader] node_modules/@types/core-js/index.d.ts:355:48
    Cannot find name 'PropertyKey'.

[at-loader] node_modules/@types/core-js/index.d.ts:356:52
    Cannot find name 'PropertyKey'.

[at-loader] node_modules/@types/core-js/index.d.ts:357:34
    Cannot find name 'PropertyKey'.

[at-loader] node_modules/@types/core-js/index.d.ts:358:34
    Cannot find name 'PropertyKey'.

[at-loader] node_modules/@types/core-js/index.d.ts:359:34
    Cannot find name 'PropertyKey'.

[at-loader] node_modules/@types/core-js/index.d.ts:360:61
    Cannot find name 'PropertyKey'.

[at-loader] node_modules/@types/core-js/index.d.ts:361:60
    Cannot find name 'PropertyKey'.

[at-loader] node_modules/@types/core-js/index.d.ts:362:65
    Cannot find name 'PropertyKey'.

[at-loader] node_modules/@types/core-js/index.d.ts:362:97
    Cannot find name 'PropertyKey'.

[at-loader] node_modules/@types/core-js/index.d.ts:363:60
    Cannot find name 'PropertyKey'.

[at-loader] node_modules/@types/core-js/index.d.ts:364:58
    Cannot find name 'PropertyKey'.

[at-loader] node_modules/@types/core-js/index.d.ts:365:59
    Cannot find name 'PropertyKey'.

[at-loader] node_modules/@types/core-js/index.d.ts:366:58
    Cannot find name 'PropertyKey'.

[at-loader] node_modules/@types/core-js/index.d.ts:367:61
    Cannot find name 'PropertyKey'.

[at-loader] node_modules/@types/core-js/index.d.ts:367:117
    Cannot find name 'PropertyKey'.

[at-loader] node_modules/@types/core-js/index.d.ts:368:42
    Cannot find name 'PropertyKey'.

[at-loader] node_modules/@types/core-js/index.d.ts:370:81
    Cannot find name 'PropertyKey'.

[at-loader] node_modules/@types/core-js/index.d.ts:371:78
    Cannot find name 'PropertyKey'.

[at-loader] node_modules/@types/core-js/index.d.ts:372:76
    Cannot find name 'PropertyKey'.

[at-loader] node_modules/@types/core-js/index.d.ts:373:73
    Cannot find name 'PropertyKey'.

[at-loader] node_modules/@types/core-js/index.d.ts:436:6
    Cannot find name 'Symbol'.

[at-loader] node_modules/@types/core-js/index.d.ts:469:59
    Cannot find name 'PropertyKey'.

[at-loader] node_modules/@types/core-js/index.d.ts:470:59
    Cannot find name 'PropertyKey'.

[at-loader] node_modules/@types/core-js/index.d.ts:472:48
    Cannot find name 'PropertyKey'.

[at-loader] node_modules/@types/core-js/index.d.ts:473:69
    Cannot find name 'PropertyKey'.

[at-loader] node_modules/@types/core-js/index.d.ts:477:40
    Cannot find name 'PropertyKey'.

[at-loader] node_modules/@types/core-js/index.d.ts:479:48
    Cannot find name 'PropertyKey'.

[at-loader] node_modules/@types/core-js/index.d.ts:695:55
    Cannot find name 'PropertyKey'.

[at-loader] node_modules/@types/core-js/index.d.ts:696:45
    Cannot find name 'PropertyKey'.

[at-loader] node_modules/@types/core-js/index.d.ts:712:46
    Cannot find name 'Iterable'.

[at-loader] node_modules/@types/core-js/index.d.ts:713:43
    Cannot find name 'Iterable'.

[at-loader] node_modules/@types/core-js/index.d.ts:829:20
    Cannot find name 'PromiseConstructor'.

[at-loader] node_modules/@types/core-js/index.d.ts:844:32
    Cannot find name 'Iterable'.

[at-loader] node_modules/@types/core-js/index.d.ts:848:39
    Cannot find name 'Iterable'.

[at-loader] node_modules/@types/core-js/index.d.ts:848:53
    Cannot find name 'Iterator'.

[at-loader] node_modules/@types/core-js/index.d.ts:1486:36
    Property 'for' does not exist on type 'SymbolConstructor'.

[at-loader] node_modules/@types/core-js/index.d.ts:1490:43
    Property 'hasInstance' does not exist on type 'SymbolConstructor'.

[at-loader] node_modules/@types/core-js/index.d.ts:1494:50
    Property 'isConcatSpreadable' does not exist on type 'SymbolConstructor'.

[at-loader] node_modules/@types/core-js/index.d.ts:1498:40
    Property 'iterator' does not exist on type 'SymbolConstructor'.

[at-loader] node_modules/@types/core-js/index.d.ts:1502:38
    Property 'keyFor' does not exist on type 'SymbolConstructor'.

[at-loader] node_modules/@types/core-js/index.d.ts:1506:37
    Property 'match' does not exist on type 'SymbolConstructor'.

[at-loader] node_modules/@types/core-js/index.d.ts:1510:39
    Property 'replace' does not exist on type 'SymbolConstructor'.

[at-loader] node_modules/@types/core-js/index.d.ts:1514:38
    Property 'search' does not exist on type 'SymbolConstructor'.

[at-loader] node_modules/@types/core-js/index.d.ts:1518:39
    Property 'species' does not exist on type 'SymbolConstructor'.

[at-loader] node_modules/@types/core-js/index.d.ts:1522:37
    Property 'split' does not exist on type 'SymbolConstructor'.

[at-loader] node_modules/@types/core-js/index.d.ts:1526:43
    Property 'toPrimitive' does not exist on type 'SymbolConstructor'.

[at-loader] node_modules/@types/core-js/index.d.ts:1530:43
    Property 'toStringTag' does not exist on type 'SymbolConstructor'.

[at-loader] node_modules/@types/core-js/index.d.ts:1534:43
    Property 'unscopables' does not exist on type 'SymbolConstructor'.

[at-loader] node_modules/@types/core-js/index.d.ts:2305:36
    Property 'for' does not exist on type 'SymbolConstructor'.

[at-loader] node_modules/@types/core-js/index.d.ts:2309:43
    Property 'hasInstance' does not exist on type 'SymbolConstructor'.

[at-loader] node_modules/@types/core-js/index.d.ts:2313:50
    Property 'isConcatSpreadable' does not exist on type 'SymbolConstructor'.

[at-loader] node_modules/@types/core-js/index.d.ts:2317:40
    Property 'iterator' does not exist on type 'SymbolConstructor'.

[at-loader] node_modules/@types/core-js/index.d.ts:2321:38
    Property 'keyFor' does not exist on type 'SymbolConstructor'.

[at-loader] node_modules/@types/core-js/index.d.ts:2325:37
    Property 'match' does not exist on type 'SymbolConstructor'.

[at-loader] node_modules/@types/core-js/index.d.ts:2329:39
    Property 'replace' does not exist on type 'SymbolConstructor'.

[at-loader] node_modules/@types/core-js/index.d.ts:2333:38
    Property 'search' does not exist on type 'SymbolConstructor'.

[at-loader] node_modules/@types/core-js/index.d.ts:2337:39
    Property 'species' does not exist on type 'SymbolConstructor'.

[at-loader] node_modules/@types/core-js/index.d.ts:2341:37
    Property 'split' does not exist on type 'SymbolConstructor'.

[at-loader] node_modules/@types/core-js/index.d.ts:2345:43
    Property 'toPrimitive' does not exist on type 'SymbolConstructor'.

[at-loader] node_modules/@types/core-js/index.d.ts:2349:43
    Property 'toStringTag' does not exist on type 'SymbolConstructor'.

[at-loader] node_modules/@types/core-js/index.d.ts:2353:43
    Property 'unscopables' does not exist on type 'SymbolConstructor'.

[at-loader] node_modules/rxjs/Observable.d.ts:68:60
    'Promise' only refers to a type, but is being used as a value here.

[at-loader] node_modules/rxjs/Subject.d.ts:16:22
    Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
      Type 'Observable<T>' is not assignable to type 'Observable<R>'.
        Type 'T' is not assignable to type 'R'.

[at-loader] node_modules/rxjs/observable/dom/WebSocketSubject.d.ts:23:22
    Class 'WebSocketSubject<T>' incorrectly extends base class 'AnonymousSubject<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => WebSocketSubject<R>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<T>'.
      Type 'WebSocketSubject<R>' is not assignable to type 'Observable<T>'.
        Types of property 'operator' are incompatible.
          Type 'Operator<any, R>' is not assignable to type 'Operator<any, T>'.
            Type 'R' is not assignable to type 'T'.

[at-loader] node_modules/rxjs/operator/toPromise.d.ts:3:79
    'Promise' only refers to a type, but is being used as a value here.

[at-loader] src/app/containers/patients.ts:103:25
    Property 'find' does not exist on type 'DoctorsModel[]'.

[at-loader] src/app/store/helper.ts:10:32
    Property 'assign' does not exist on type 'ObjectConstructor'.

[at-loader] src/app/store/helper.ts:16:32
    Property 'assign' does not exist on type 'ObjectConstructor'.

[at-loader] src/app/store/helper.ts:23:32
    Property 'assign' does not exist on type 'ObjectConstructor'.

[at-loader] src/app/store/helper.ts:29:32
    Property 'assign' does not exist on type 'ObjectConstructor'.

[at-loader] src/app/store/index.ts:52:21
    Property 'assign' does not exist on type 'ObjectConstructor'.

[at-loader] src/app/store/index.ts:60:21
    Property 'assign' does not exist on type 'ObjectConstructor'.

**Comment by shiamalon** [comment]
same issue :|

**Comment by shiamalon** [comment]
Working for me with:
npm install rxjs@^5.0.1 -s

and updated tsconfig.json:
{
  "compilerOptions": {
    "module": "commonjs",
    **"target": "es6",**
    "outDir": "dist",
    "rootDir": "src",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "forceConsistentCasingInFileNames": true,
    "types": [
      "node",
      "core-js"
    ],
    **"skipLibCheck": true**
  },
  "compileOnSave": false,
  "buildOnSave": false
}

**Comment by andreshg112** [comment]
Thank you!
It worked for me too!
I didn't have to change the tsconfig.js to make it work.

**Comment by gorums** [comment]
@shiamalon I added your code to fix that issues in the release 0.6.0 thx
